### ISSUE TITLE
How exclude subs

### ISSUE THREAD

**Issue by NomisCiri** [NomisCiri/eeg_manypipes_arc#10]
Should the exclude subjects script be a standalone script that just runs and puts out a json or csv that specifies which subjects do not satisfy our criterion, or should it be integrated in the current flow that takes each subject as command line argument separately?

i would've done the fist because this is something that needs to run only once...

so basically, define all subs in a list and loop through them here

```python
fpath_set = fpath_ds / "sourcedata" / "events" / f"EMP{sub:02}_events.csv"
```

or not?

**Comment by sappelhoff** [comment]
I agree: let's do a standalone script that we run once, and then based on the output, we decide which subjs to exclude. Then we enter the subj IDs here:

https://github.com/NomisCiri/eeg_manypipes_arc/blob/a86d96c1c85e3cf5fedff4d802ef76e911be3484/config.py#L46-L48

with a description that we base this choice on our script

**Comment by sappelhoff** [comment]
note that running over subjs can then be done by

```python
from config import SUBJS
for sub in SUBJS:
    pass
```

see:

https://github.com/NomisCiri/eeg_manypipes_arc/blob/a86d96c1c85e3cf5fedff4d802ef76e911be3484/config.py#L50-L51

and (for cli use): 

https://github.com/NomisCiri/eeg_manypipes_arc/blob/a86d96c1c85e3cf5fedff4d802ef76e911be3484/01_find_bads.py#L47-L48

**Comment by NomisCiri** [comment]
you are really amazing 🌈
