### ISSUE TITLE
H2

### ISSUE THREAD

**Issue by NomisCiri** [NomisCiri/eeg_manypipes_arc#12]
I have some code and report in place for testing the hypotheses specified under h2
I am uncertain whether i do the permutation test correctly, coulr really use your input :)
As of now, none of the hypotheses seem to turn out significant.

**Comment by sappelhoff** [comment]
Do you want to open a PR from your branch so we can continue discussion there? Or meeting? Or both?

**Comment by NomisCiri** [comment]
i made a pr. but there is some stuff missing
maybe a meeting is reasonable, but i think it would make most sense after you have looked at my code?
 i will work on the basic script for h3&4 in the meantime
