### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by sappelhoff** [NomisCiri/eeg_manypipes_arc#17]
once we have submitted all files for the project, we should register this repository with https://zenodo.org/ (via your account Simon, you can log in there via GitHub) and make a GitHub release of the code.

As a result, the code will be automatically archived, and that's nice because we get a DOI and some peace of mind that even if GitHub is gone, our code is still there

I can tell you about this in a call though :) very simple to do

**Comment by NomisCiri** [comment]
i close this :)
